# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test against latest dynesty

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONDA_PATH: /opt/conda/

jobs:
  build:

    name: ${{ matrix.python.name }} unit tests
    runs-on: ubuntu-latest
    container: ghcr.io/bilby-dev/bilby-python${{ matrix.python.short-version }}:latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - name: Python 3.12
            version: 3.12
            short-version: 312

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Install package
      run: |
        # activate env so that conda list shows the correct environment
        source $CONDA_PATH/bin/activate python${{ matrix.python.short-version }}
        python -m pip install .
        python -m pip install git+https://github.com/joshspeagle/dynesty@master
        conda list --show-channel-urls
      shell: bash
    - name: Run unit tests
      run: |
        python -m pytest --durations 10 -k dynesty
    - name: Run sampler tests
      run: |
        python -m pytest test/integration/sampler_run_test.py --durations 10 -v -k dynesty
